image: Visual Studio 2019 Preview
install:
  - cinst fake

build_script:
  - cmd: fake.exe run build.fsx --parallel 1

on_finish:
  - sh: |
      find "./testResult/" -type f -name '*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/xunit/$APPVEYOR_JOB_ID"

test: off
