version: "3.4"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock:ro"

  identity-api:
    environment:
      - IDENTITY_FRONTENDHOST=http://${DNS_NAME_OR_IP}
      - IDENTITY_ISSUER=http://localhost:5105
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.identity-api.rule=Host(`identity.${DNS_NAME_OR_IP}`)"
    #   - "traefik.http.routers.identity-api.entrypoints=web"
    #   - "traefik.http.routers.identity-api.middlewares=cors@docker"

  strive:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.${DNS_NAME_OR_IP}`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.strive.loadbalancer.healthcheck.path=/health/ready"
      - "traefik.http.routers.api.middlewares=cors@docker"
      # Cors Middleware
      - "traefik.http.middlewares.cors.headers.accessControlAllowOriginList=http://${DNS_NAME_OR_IP}"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=*,X-Requested-With,X-SignalR-User-Agent"
      - "traefik.http.middlewares.cors.headers.accessControlAllowCredentials=true"
    environment:
      - SFU__UrlTemplate=http://sfu.${DNS_NAME_OR_IP}/{0}
      - Authentication__NoSslRequired=true
      - Authentication__Issuer=http://localhost:5105
      - Authentication__Authority=http://host.docker.internal:5105

  webspa:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spa.rule=Host(`${DNS_NAME_OR_IP}`)"
      - "traefik.http.routers.spa.entrypoints=web"
      - "traefik.http.services.webspa.loadbalancer.healthcheck.path=/health"
    environment:
      - App__IdentityUrl=http://localhost:5105/
      - App__ConferenceUrl=http://api.${DNS_NAME_OR_IP}/
      - App__SignalrHubUrl=http://api.${DNS_NAME_OR_IP}/signalr
      - App__EquipmentSignalrHubUrl=http://api.${DNS_NAME_OR_IP}/equipment-signalr
      - App__FrontendUrl=http://${DNS_NAME_OR_IP}/

  sfu:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sfu.rule=Host(`sfu.${DNS_NAME_OR_IP}`)"
      - "traefik.http.routers.sfu.entrypoints=web"
      - "traefik.http.services.sfu.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.sfu.loadbalancer.healthcheck.port=9000"
      - "traefik.http.services.sfu.loadbalancer.server.port=3000"
      - "traefik.http.routers.sfu.middlewares=cors@docker"
