version: "3.4"

services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      # Cors Middleware
      - "traefik.http.middlewares.cors.headers.accessControlAllowOriginList=https://${DNS_NAME_OR_IP}"
      - "traefik.http.middlewares.cors.headers.accessControlAllowMethods=*"
      - "traefik.http.middlewares.cors.headers.accessControlAllowHeaders=*,X-Requested-With,X-SignalR-User-Agent"
      - "traefik.http.middlewares.cors.headers.accessControlAllowCredentials=true"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"

  identity-api:
    environment:
      - IdentityServer__SpaClientHost=https://${DNS_NAME_OR_IP}
      - IdentityServer__Issuer=https://identity.${DNS_NAME_OR_IP}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.identity-api.rule=Host(`identity.${DNS_NAME_OR_IP}`)"
      - "traefik.http.routers.identity-api.entrypoints=websecure"
      - "traefik.http.routers.identity-api.middlewares=cors@docker"
      - "traefik.http.routers.identity-api.tls=true"

  strive:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.${DNS_NAME_OR_IP}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.services.strive.loadbalancer.healthcheck.path=/health/ready"
      - "traefik.http.routers.api.middlewares=cors@docker"
      - "traefik.http.routers.api.tls=true"
    environment:
      - SFU__UrlTemplate=https://sfu.${DNS_NAME_OR_IP}/{0}
      - Authentication__NoSslRequired=true
      - Authentication__Issuer=https://identity.${DNS_NAME_OR_IP}
      - Authentication__Authority=http://host.docker.internal:5105

  webspa:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spa.rule=Host(`${DNS_NAME_OR_IP}`)"
      - "traefik.http.routers.spa.entrypoints=websecure"
      - "traefik.http.services.webspa.loadbalancer.healthcheck.path=/health"
      - "traefik.http.routers.spa.tls=true"
    environment:
      - App__IdentityUrl=https://identity.${DNS_NAME_OR_IP}
      - App__FrontendUrl=https://${DNS_NAME_OR_IP}
      - App__ConferenceUrl=https://api.${DNS_NAME_OR_IP}/
      - App__SignalrHubUrl=https://api.${DNS_NAME_OR_IP}/signalr
      - App__EquipmentSignalrHubUrl=https://api.${DNS_NAME_OR_IP}/equipment-signalr

  sfu:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sfu.rule=Host(`sfu.${DNS_NAME_OR_IP}`)"
      - "traefik.http.routers.sfu.entrypoints=websecure"
      - "traefik.http.services.sfu.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.sfu.loadbalancer.healthcheck.port=9000"
      - "traefik.http.services.sfu.loadbalancer.server.port=3000"
      - "traefik.http.routers.sfu.middlewares=cors@docker"
      - "traefik.http.routers.sfu.tls=true"
