version: "3.4"

services:
  traefik:
    volumes:
      - "./acme.json:/acme.json"

  identity-api:
    labels:
      - "traefik.http.routers.identity-api.tls.certresolver=letsEncrypt"

  strive:
    labels:
      - "traefik.http.routers.api.tls.certresolver=letsEncrypt"

  webspa:
    labels:
      - "traefik.http.routers.spa.tls.certresolver=letsEncrypt"

  sfu:
    labels:
      - "traefik.http.routers.sfu.tls.certresolver=letsEncrypt"
    environment:
      - MEDIASOUP_MIN_PORT
      - MEDIASOUP_MAX_PORT
    network_mode: host # we need to export a large port range https://docs.docker.com/network/host/
