version: "3.4"

services:
  nosqldata:
    image: mongo

  rabbitmq:
    image: masstransit/rabbitmq

  identity-api:
    image: ${DOCKER_REGISTRY-}identityapi
    build: ./Services/Identity/Identity.API

  sfu:
    image: ${DOCKER_REGISTRY-}sfu
    build: "./Services/SFU"
    depends_on:
      - rabbitmq

  paderconference:
    image: ${DOCKER_REGISTRY-}paderconference
    build:
      context: .
      dockerfile: Services/ConferenceManagement/PaderConference/Dockerfile
    depends_on:
      - nosqldata
      - rabbitmq
      - identity-api

  webspa:
    image: ${DOCKER_REGISTRY-}webspa
    build: "./Web/WebSPA"
    depends_on:
      - identity-api
      - sfu
      - paderconference
