version: "3.4"

services:
  nosqldata:
    ports:
      - "27017:27017"

  rabbitmq:
    ports:
      - "5672:5672"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT}
    ports:
      - "5105:80"

  paderconference:
    environment:
      - ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT}
      - Authentication__Authority=http://identity-api
      - KeyValueDatabase__UseInMemory=true
      - RabbitMq__UseInMemory=false
      - RabbitMq__RabbitMq__Host=amqp://rabbitmq
      - MongoDb__ConnectionString=mongodb://nosqldata
      - SFU__TokenSecret=${PADERCONFERENCE_TOKEN_SECRET}
      - SFU__ApiKey=${PADERCONFERENCE_API_KEY}
    ports:
      - "5101:80"

  webspa:
    ports:
      - "5100:80"

  sfu:
    environment:
      - SERVER_ENVIRONMENT=${APP_ENVIRONMENT}
      - API_CONFERENCE_MANAGEMENT=http://paderconference/v1/sfu/{conferenceId}?apiKey=${PADERCONFERENCE_API_KEY}
      - AMQP_CONNECTION_STRING=amqp://rabbitmq
      - API_TOKEN_SECRET=${PADERCONFERENCE_TOKEN_SECRET}
      - MEDIASOUP_ANNOUNCED_IP=${DNS_NAME_OR_IP}
    ports:
      - "5102:3000"
      - "40000:49999"
      - "9000:9000"
