version: "3.4"

services:
  traefik:
    volumes:
      - "./acme.json:/acme.json"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  identity-api:
    labels:
      - "traefik.http.routers.identity-api.tls.certresolver=letsEncrypt"

  strive:
    labels:
      - "traefik.http.routers.api.tls.certresolver=letsEncrypt"

  webspa:
    labels:
      - "traefik.http.routers.spa.tls.certresolver=letsEncrypt"

  sfu:
    build:
      args:
        - MEDIASOUP_MIN_PORT=${MEDIASOUP_MIN_PORT}
        - MEDIASOUP_MAX_PORT=${MEDIASOUP_MAX_PORT}
    labels:
      - "traefik.http.routers.sfu.tls.certresolver=letsEncrypt"
    environment:
      - DEBUG=strive-mediasoup**
      - API_CONFERENCE_MANAGEMENT=http://0.0.0.0:5101/v1/sfu/{conferenceId}?apiKey=${STRIVE_API_KEY}
      - AMQP_CONNECTION_STRING=amqp://0.0.0.0:5672
    network_mode: host # we need to export a large port range https://docs.docker.com/network/host/
