name: Cypress E2E tests
on:
  push:
    paths:
      - src/**
      - .github/workflows/e2e-tests.yml

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/
    steps:
    - uses: actions/checkout@v2
    - name: Build and run docker compose
      run: chmod +x ./compose.sh
      run: ./compose.sh -f .\docker-compose.e2e.yml up --exit-code-from e2e
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}